### ISSUE TITLE
New tag/release?

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/controller-lifecycle-operator-sdk#14]
Hi @jakub-dzon I think it would be great to have a new tag and/or release which includes:  https://github.com/kubevirt/controller-lifecycle-operator-sdk/pull/13

**Comment by jakub-dzon** [comment]
Done: https://github.com/kubevirt/controller-lifecycle-operator-sdk/releases/tag/v0.1.2

**Comment by mhenriks** [comment]
Thank you @jakub-dzon!
