### ISSUE TITLE
Downgrades are rejected

### ISSUE THREAD

**Issue by vasiliy-ul** [kubevirt/controller-lifecycle-operator-sdk#20]
Hi, I recently faced an issue when trying to switch to a lower version of CDI. I hit the following error:

https://github.com/kubevirt/controller-lifecycle-operator-sdk/blob/198721096cb3a8e15914e154e518adbf55f96b0c/pkg/sdk/reconciler/versions.go#L40

There might be cases when e.g. a new update introduces bugs and users may want to rollback. For sure that may bring compatibility issues. Bur e.g. switching back to a lower patch version should be safe: `x.x.1` -> `x.x.0`. And even if its not a patch-level downgrade perhaps a user may still want to do that "on own risk". Is there any specific reason to reject downgrades?

**Comment by vasiliy-ul** [comment]
ping @jakub-dzon , @mhenriks (just found you as contributors in the project history). Maybe you have some thoughts on the topic?

**Comment by jakub-dzon** [comment]
I have just extracted and generalized the code from CDI and I don't know the rationale behind the original design. Maybe Michael would be able to explain.
